2012/01/31 00:41:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('yii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=yii
2012/01/31 00:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yiic".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('yiic')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=yiic
2012/01/31 00:42:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yiig".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('yiig')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=yiig
2012/01/31 00:42:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=gii
2012/01/31 00:42:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=gii
2012/01/31 00:43:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=gii
2012/01/31 00:43:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=gii
2012/01/31 00:43:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=gii
2012/01/31 00:56:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Usuarios".' in C:\xampp\htdocs\yii118\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(262): CController->missingAction('Usuarios')
#1 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('Usuarios')
#2 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/Usuarios')
#3 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/guiasyii/index.php?r=site/Usuarios
2012/01/31 00:57:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Usuarios".' in C:\xampp\htdocs\yii118\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(262): CController->missingAction('Usuarios')
#1 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('Usuarios')
#2 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/Usuarios')
#3 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/guiasyii/index.php?r=site/Usuarios
2012/01/31 00:57:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Usuarios".' in C:\xampp\htdocs\yii118\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(262): CController->missingAction('Usuarios')
#1 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('Usuarios')
#2 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/Usuarios')
#3 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/guiasyii/index.php?r=site/Usuarios
2012/01/31 07:19:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "estado/admin".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('estado/admin')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=estado/admin
2012/01/31 07:20:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "estado/admin".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('estado/admin')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=estado/admin
2012/01/31 07:20:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "estado/admin".' in C:\xampp\htdocs\yii118\framework\web\CWebApplication.php:281
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('estado/admin')
#1 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#2 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#3 {main} REQUEST_URI=/guiasyii/index.php?r=estado/admin
2012/01/31 16:48:11 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(21): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:50:48 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:50:56 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:51:16 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:51:40 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:51:46 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:53:12 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 16:54:18 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(59): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:05:39 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuarios" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuarios')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:07:13 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuarios" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(23): CComponent->__get('usuarios')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:15:49 [error] [exception.CException] exception 'CException' with message 'Propiedad "LoginForm"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(2063): CComponent->__get('usuario')
#1 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(1791): CHtml::resolveValue(Object(LoginForm), 'usuario')
#2 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(1199): CHtml::activeInputField('text', Object(LoginForm), 'usuario', Array)
#3 C:\xampp\htdocs\yii118\framework\web\widgets\CActiveForm.php(568): CHtml::activeTextField(Object(LoginForm), 'usuario', Array)
#4 C:\xampp\htdocs\guiasyii\protected\views\site\login.php(25): CActiveForm->textField(Object(LoginForm), 'usuario')
#5 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(92): CController->render('login', Array)
#10 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#15 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#17 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#18 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:15:53 [error] [exception.CException] exception 'CException' with message 'Propiedad "LoginForm"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(2063): CComponent->__get('usuario')
#1 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(1791): CHtml::resolveValue(Object(LoginForm), 'usuario')
#2 C:\xampp\htdocs\yii118\framework\web\helpers\CHtml.php(1199): CHtml::activeInputField('text', Object(LoginForm), 'usuario', Array)
#3 C:\xampp\htdocs\yii118\framework\web\widgets\CActiveForm.php(568): CHtml::activeTextField(Object(LoginForm), 'usuario', Array)
#4 C:\xampp\htdocs\guiasyii\protected\views\site\login.php(25): CActiveForm->textField(Object(LoginForm), 'usuario')
#5 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(92): CController->render('login', Array)
#10 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#15 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#17 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#18 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:18:30 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(23): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:23:31 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:25:04 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(22): CComponent->__get('usuario')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:25:55 [error] [php] include(Usuario.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii118\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(23): spl_autoload_call()
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CInlineValidator->validate()
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): LoginForm->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): SiteController->runAction()
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): SiteController->run()
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController()
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CWebApplication->run()
REQUEST_URI=/guiasyii/index.php?r=site/login
in C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php (51)
in C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php (88)
2012/01/31 17:27:13 [error] [php] include(Usuario.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\xampp\htdocs\yii118\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(23): spl_autoload_call()
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CInlineValidator->validate()
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): LoginForm->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): SiteController->runAction()
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): SiteController->run()
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController()
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CWebApplication->run()
REQUEST_URI=/guiasyii/index.php?r=site/login
in C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php (51)
in C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php (88)
2012/01/31 17:28:49 [error] [exception.CException] exception 'CException' with message 'Propiedad "UserIdentity"."pass" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(26): CComponent->__get('pass')
#1 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#3 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#4 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:42:58 [error] [exception.CException] exception 'CException' with message 'Propiedad "Usuarios"."password" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\db\ar\CActiveRecord.php(129): CComponent->__get('password')
#1 C:\xampp\htdocs\guiasyii\protected\models\Usuarios.php(16): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(26): Usuarios->validatePassword('enrique')
#3 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#5 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#6 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#8 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#13 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 17:44:12 [error] [exception.CException] exception 'CException' with message 'Propiedad "Usuarios"."password" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\db\ar\CActiveRecord.php(129): CComponent->__get('password')
#1 C:\xampp\htdocs\guiasyii\protected\models\Usuarios.php(16): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\guiasyii\protected\components\UserIdentity.php(26): Usuarios->validatePassword('enrique')
#3 C:\xampp\htdocs\guiasyii\protected\models\LoginForm.php(51): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii118\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('pass', Array)
#5 C:\xampp\htdocs\yii118\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'pass')
#6 C:\xampp\htdocs\yii118\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(88): CModel->validate()
#8 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('login')
#13 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/guiasyii/index.php?r=site/login
2012/01/31 18:24:03 [error] [exception.CException] exception 'CException' with message 'Propiedad "CWebApplication"."Usuario" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\base\CModule.php(88): CComponent->__get('Usuario')
#1 C:\xampp\htdocs\guiasyii\protected\views\site\index.php(3): CModule->__get('Usuario')
#2 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('')
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/guiasyii/index.php
2012/01/31 19:04:26 [error] [exception.CException] exception 'CException' with message 'Propiedad "CWebUser"."pass" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CWebUser.php(124): CComponent->__get('pass')
#1 C:\xampp\htdocs\guiasyii\protected\views\site\index.php(3): CWebUser->__get('pass')
#2 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('')
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/guiasyii/index.php
2012/01/31 19:04:45 [error] [exception.CException] exception 'CException' with message 'Propiedad "CWebUser"."password" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CWebUser.php(124): CComponent->__get('password')
#1 C:\xampp\htdocs\guiasyii\protected\views\site\index.php(3): CWebUser->__get('password')
#2 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('')
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/guiasyii/index.php
2012/01/31 19:32:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('index')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('Usuarios/index')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=Usuarios/index
2012/01/31 19:43:03 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=usuarios/admin
2012/01/31 19:43:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=usuarios/admin
2012/01/31 19:43:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=usuarios/admin
2012/01/31 19:45:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=usuarios/admin
2012/01/31 19:47:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=usuarios/admin
2012/01/31 19:53:40 [error] [exception.CException] exception 'CException' with message 'Propiedad "CWebApplication"."isGuest" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\base\CModule.php(88): CComponent->__get('isGuest')
#1 C:\xampp\htdocs\guiasyii\protected\views\site\index.php(3): CModule->__get('isGuest')
#2 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('index')
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/index')
#13 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/guiasyii/index.php?r=site/index
2012/01/31 19:54:58 [error] [exception.CException] exception 'CException' with message 'Propiedad "CWebApplication"."isGuest" no se encuentra definida.' in C:\xampp\htdocs\yii118\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\base\CModule.php(88): CComponent->__get('isGuest')
#1 C:\xampp\htdocs\guiasyii\protected\views\site\index.php(3): CModule->__get('isGuest')
#2 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(119): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii118\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(779): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii118\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('index')
#12 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('site/index')
#13 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/guiasyii/index.php?r=site/index
2012/01/31 20:04:35 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\guiasyii\protected\views\site\index.php:3)
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(866): SiteController->renderFile()
#1 C:\xampp\htdocs\yii118\framework\web\CController.php(779): SiteController->renderPartial()
#2 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(278): SiteController->runAction()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): SiteController->run()
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController()
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CWebApplication->run()
REQUEST_URI=/guiasyii/index.php?r=site/index
in C:\xampp\htdocs\guiasyii\protected\views\site\index.php (3)
in C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\guiasyii\index.php (13)
2012/01/31 20:04:57 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\guiasyii\protected\views\site\index.php:3)
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(866): SiteController->renderFile()
#1 C:\xampp\htdocs\yii118\framework\web\CController.php(779): SiteController->renderPartial()
#2 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(278): SiteController->runAction()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): SiteController->run()
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController()
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CWebApplication->run()
REQUEST_URI=/guiasyii/index.php?r=site/index
in C:\xampp\htdocs\guiasyii\protected\views\site\index.php (3)
in C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\guiasyii\index.php (13)
2012/01/31 20:05:40 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\guiasyii\protected\views\site\index.php:3)
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\CController.php(866): SiteController->renderFile()
#1 C:\xampp\htdocs\yii118\framework\web\CController.php(779): SiteController->renderPartial()
#2 C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii118\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii118\framework\web\CController.php(300): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(278): SiteController->runAction()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): SiteController->run()
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController()
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CWebApplication->run()
REQUEST_URI=/guiasyii/index.php?r=site/index
in C:\xampp\htdocs\guiasyii\protected\views\site\index.php (3)
in C:\xampp\htdocs\guiasyii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\guiasyii\index.php (13)
2012/01/31 20:13:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('guias/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=guias/admin
2012/01/31 20:19:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:19:49 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:20:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:20:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:20:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:20:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:20:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
2012/01/31 20:21:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('delete')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/delete')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes%2Fdelete&id=1&ajax=origenes-grid
2012/01/31 22:18:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php:158
Stack trace:
#0 C:\xampp\htdocs\yii118\framework\web\auth\CAccessControlFilter.php(120): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 C:\xampp\htdocs\yii118\framework\web\filters\CFilter.php(39): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii118\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii118\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii118\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii118\framework\web\CController.php(283): CFilterChain->run()
#6 C:\xampp\htdocs\yii118\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(277): CController->run('admin')
#8 C:\xampp\htdocs\yii118\framework\web\CWebApplication.php(136): CWebApplication->runController('origenes/admin')
#9 C:\xampp\htdocs\yii118\framework\base\CApplication.php(158): CWebApplication->processRequest()
#10 C:\xampp\htdocs\guiasyii\index.php(13): CApplication->run()
#11 {main} REQUEST_URI=/guiasyii/index.php?r=origenes/admin
